version: '3'
services:
# The first node and config in the first datacenter.
    node1:
        image: datastax/dse-server:6.8.16-ubi7
        container_name: DSE-6_node1
        hostname: node1
        # use static ip address
        networks:
            dc1ring:
                ipv4_address: 172.30.0.2
        # Maps cassandra exercises to a local folder.
        # This preserves data across container restarts.
        volumes:
            - ./CompartidoCassandra:/opt/dse/CompartidoCassandra
        # Docker container environment variable. We are using the
        # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
        # across clusters. We are also declaring that node1 is a seed node etc.
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=dse51_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        # Exposing ports for inter cluster communication
        expose:
            # Intra-node communication
            - 7000
            # TLS intra-node communication
            - 7001
            # JMX
            - 7199
            # CQL
            - 9042
            # CQL SSL
            - 9142
        ports:
            - 9042:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    node2:
        image: datastax/dse-server:6.8.16-ubi7
        container_name: DSE-6_node2
        hostname: node2
        networks:
            dc1ring:
                ipv4_address: 172.30.0.3
        volumes:
            - ./CompartidoCassandra:/opt/dse/CompartidoCassandra
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=dse51_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9142
        ports:
            - 9043:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        depends_on:
            - node1
    node3:
        image: datastax/dse-server:6.8.16-ubi7
        container_name: DSE-6_node3
        hostname: node3
        networks:
            dc1ring:
                ipv4_address: 172.30.0.4
        volumes:
            - ./CompartidoCassandra:/opt/dse/CompartidoCassandra
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=dse51_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9142
        ports:
            - 9044:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        depends_on:
            - node1
    node4:
        image: datastax/dse-server:6.8.16-ubi7
        container_name: DSE-6_node4
        hostname: node4
        networks:
            dc1ring:
                ipv4_address: 172.30.0.5
        volumes:
            - ./CompartidoCassandra:/opt/dse/CompartidoCassandra
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=dse51_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9142
        ports:
            - 9045:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        depends_on:
            - node1
    node5:
        image: datastax/dse-server:6.8.16-ubi7
        container_name: DSE-6_node5
        hostname: node5
        networks:
            dc1ring:
                ipv4_address: 172.30.0.6
        volumes:
            - ./CompartidoCassandra:/opt/dse/CompartidoCassandra
        environment:
            - DS_LICENSE=accept
            - SEEDS=node1
            - START_RPC=false
            - CLUSTER_NAME=dse51_cluster
            - NUM_TOKENS=3
            - DC=DC1
            - RACK=RAC1
            - MAX_HEAP_SIZE=1000000000
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9142
        ports:
            - 9046:9042
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        depends_on:
            - node1


    studio:  # Datastax Studio provides convenient web interface to work directly with the Apache Cassandra or DataStax Enterprise
        image: datastax/dse-studio:6.7.0
        container_name: DSE-6_studio
        volumes:
            - ./CompartidoCassandra:/opt/dse/CompartidoCassandra
        ports:
        - 9091:9091 # Exposes port to be available externally
        depends_on:
        - node1 # Needs DSE to be running
        environment:
            - DS_LICENSE=accept
        networks:
            dc1ring:
                ipv4_address: 172.30.0.7
        expose:
            # Intra-node communication
            - 7000
            # TLS intra-node communication
            - 7001
            # JMX
            - 7199
            # CQL
            - 9042
            # CQL SSL
            - 9142                   
networks:
    dc1ring:
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16